### ISSUE TITLE
Build issues MAC after update to 10.13.4 

### ISSUE THREAD

**Issue by Remco75** [cryptonotefoundation/cryptonote#253]
Might also have to do with xcode update.
After the update I get the flolowing error:
/XXX/src/crypto/slow-hash.cpp:54:7: error: '~cn_context' has a non-throwing exception specification but can still throw [-Werror,-Wexceptions]
      throw bad_alloc();
      ^
/XXX/src/crypto/slow-hash.cpp:52:15: note: destructor has a implicit non-throwing exception specification
  cn_context::~cn_context() {

Can't figure out how to fix this.  Any known workarounds out there?

**Comment by ABILATA** [comment]
I am having exactly the same problem, did you find out a way to fix it?

**Comment by Remco75** [comment]
nope, did not dive deeper into it yet....

**Comment by SoraKohaku** [comment]
MAC on there still bugged. we success do seria for mac platform. look
my repo all gone +heavy and masternodes implemented soon. Heavy is
progress 80%. PoS 90%

On 5/17/18, Remco Vlierman <notifications@github.com> wrote:
> nope, did not dive deeper into it yet....
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/cryptonotefoundation/cryptonote/issues/253#issuecomment-389814549


-- 
Nur1Labs©2013
______________________________
Site Info -> Here <http://nur1labs.com/>

Easy Transaction
MoneyBookers <https://www.moneybookers.com/app/?rid=17274145>

**Comment by Remco75** [comment]
@FndNur1Labs what repo do you mean?

**Comment by SoraKohaku** [comment]
https://github.com/FndNur1Labs/CryptonoteEvo

we success added heavy feature[can disable and enable], PoS,etc just
explore. this one too old for your mac :)
